/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUnverifiedRouteImport } from './routes/admin/unverified'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAvailableRouteImport } from './routes/admin/available'
import { Route as AdminVerifiedIndexRouteImport } from './routes/admin/verified/index'
import { Route as AdminVerifiedItemIdRouteImport } from './routes/admin/verified/$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnverifiedRoute = AdminUnverifiedRouteImport.update({
  id: '/admin/unverified',
  path: '/admin/unverified',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAvailableRoute = AdminAvailableRouteImport.update({
  id: '/admin/available',
  path: '/admin/available',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerifiedIndexRoute = AdminVerifiedIndexRouteImport.update({
  id: '/admin/verified/',
  path: '/admin/verified/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerifiedItemIdRoute = AdminVerifiedItemIdRouteImport.update({
  id: '/admin/verified/$itemId',
  path: '/admin/verified/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/available': typeof AdminAvailableRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/verified/$itemId': typeof AdminVerifiedItemIdRoute
  '/admin/verified/': typeof AdminVerifiedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/available': typeof AdminAvailableRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/verified/$itemId': typeof AdminVerifiedItemIdRoute
  '/admin/verified': typeof AdminVerifiedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/available': typeof AdminAvailableRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/unverified': typeof AdminUnverifiedRoute
  '/admin/verified/$itemId': typeof AdminVerifiedItemIdRoute
  '/admin/verified/': typeof AdminVerifiedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/available'
    | '/admin/login'
    | '/admin/unverified'
    | '/admin/verified/$itemId'
    | '/admin/verified/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/available'
    | '/admin/login'
    | '/admin/unverified'
    | '/admin/verified/$itemId'
    | '/admin/verified'
  id:
    | '__root__'
    | '/'
    | '/admin/available'
    | '/admin/login'
    | '/admin/unverified'
    | '/admin/verified/$itemId'
    | '/admin/verified/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAvailableRoute: typeof AdminAvailableRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminUnverifiedRoute: typeof AdminUnverifiedRoute
  AdminVerifiedItemIdRoute: typeof AdminVerifiedItemIdRoute
  AdminVerifiedIndexRoute: typeof AdminVerifiedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/unverified': {
      id: '/admin/unverified'
      path: '/admin/unverified'
      fullPath: '/admin/unverified'
      preLoaderRoute: typeof AdminUnverifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/available': {
      id: '/admin/available'
      path: '/admin/available'
      fullPath: '/admin/available'
      preLoaderRoute: typeof AdminAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verified/': {
      id: '/admin/verified/'
      path: '/admin/verified'
      fullPath: '/admin/verified/'
      preLoaderRoute: typeof AdminVerifiedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verified/$itemId': {
      id: '/admin/verified/$itemId'
      path: '/admin/verified/$itemId'
      fullPath: '/admin/verified/$itemId'
      preLoaderRoute: typeof AdminVerifiedItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAvailableRoute: AdminAvailableRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminUnverifiedRoute: AdminUnverifiedRoute,
  AdminVerifiedItemIdRoute: AdminVerifiedItemIdRoute,
  AdminVerifiedIndexRoute: AdminVerifiedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
